// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNEFxmeTlYRBqxkcBzPGeORD7rYRTSVVM',
    appId: '1:683296600456:web:35674c63843df20467ca3d',
    messagingSenderId: '683296600456',
    projectId: 'top90-b18a3',
    authDomain: 'top90-b18a3.firebaseapp.com',
    storageBucket: 'top90-b18a3.firebasestorage.app',
    measurementId: 'G-ZV920J8CYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4VNHM6Rk_y_uOKa4S0pyDXwwjSiIxrX0',
    appId: '1:683296600456:android:3f945f12f2d9a49667ca3d',
    messagingSenderId: '683296600456',
    projectId: 'top90-b18a3',
    storageBucket: 'top90-b18a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw1HDrVmrch5XHvXrY4JnMOAf9cXmO_bQ',
    appId: '1:683296600456:ios:0f423cf3ac9743ab67ca3d',
    messagingSenderId: '683296600456',
    projectId: 'top90-b18a3',
    storageBucket: 'top90-b18a3.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw1HDrVmrch5XHvXrY4JnMOAf9cXmO_bQ',
    appId: '1:683296600456:ios:0f423cf3ac9743ab67ca3d',
    messagingSenderId: '683296600456',
    projectId: 'top90-b18a3',
    storageBucket: 'top90-b18a3.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNEFxmeTlYRBqxkcBzPGeORD7rYRTSVVM',
    appId: '1:683296600456:web:85c6affe31ee96af67ca3d',
    messagingSenderId: '683296600456',
    projectId: 'top90-b18a3',
    authDomain: 'top90-b18a3.firebaseapp.com',
    storageBucket: 'top90-b18a3.firebasestorage.app',
    measurementId: 'G-LRMLT3S4BZ',
  );
}
